### PR TITLE
Fix loose semver parsing to recognize Kotlin rules

### LINKED ISSUE #66: Update bazel rules
Update versions and checksums for bazel rules like jvm_rules_external, rules_scala, rules_kotlin, etc.

### PR DESCRIPTION
**Pull request by kamildoleglo**
Fixes #66 for Kotlin. Should work for Scala rules > v5.0.0 as long as they maintain somewhat sane versioning schema

### CODE REVIEW

File: core/src/main/kotlin/org/virtuslab/bazelsteward/core/library/SemanticVersion.kt [hunk 1]
```diff
@@ -79,7 +79,7 @@ data class SemanticVersion(
     private val strictSemVerRegex =
       Regex("""^(?<major>0|[1-9]\d*)\.(?<minor>0|[1-9]\d*)\.(?<patch>0|[1-9]\d*)(?:-(?<preRelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?<buildMetaData>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?${'$'}""")
     private val looseSemVerRegex =
-      Regex("""^(?<major>0|[1-9]\d*)(?:[.-](?<minor>(0|[1-9]\d*)))?(?:[.-]?(?<patch>(0|[1-9]\d*)))?(?:[-.]?(?<preRelease>((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)))?(?:\+(?<buildMetaData>([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*)))?${'$'}""")
+      Regex("""^[vV]?\.?(?<major>0|[1-9]\d*)(?:[.-](?<minor>(0|[1-9]\d*)))?(?:[.-]?(?<patch>(0|[1-9]\d*)))?(?:[-.]?(?<preRelease>((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)))?(?:\+(?<buildMetaData>([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*)))?${'$'}""")
```
Comment (lukaszwawrzyk) [inline core/src/main/kotlin/org/virtuslab/bazelsteward/core/library/SemanticVersion.kt:82]: it's probably not harmful, but why expect a dot after `v`?

**Review by lukaszwawrzyk — APPROVED** [review]

File: core/src/main/kotlin/org/virtuslab/bazelsteward/core/library/SemanticVersion.kt (hunk 1 above)
Comment (kamildoleglo) [reply core/src/main/kotlin/org/virtuslab/bazelsteward/core/library/SemanticVersion.kt:82]: Sometimes there are versions in that look like `v.1.0.0`
